### PR TITLE
[update] MIP-0 : Overview of MIPs

### PR DESCRIPTION
**Pull request by franck44**
# Summary

Add a list of current MDs, MIPs with their statuses, cross-refs.

### CODE REVIEW

**Comment by apenzk** [comment]
Generally i am in favor of such a list. 
- i am not sure about the location.. it could be at the bottom or in a separate file instead in order not to interrupt the read of the instructions.
- while it would be very helpful to have an overview of unmerged MDs, MIPs and MGs what is the idea of `main` ? Should it be kept clean of new ideas? 

in particular as it's helpful with unmerged MIPs and MDs. However I propose to have unmerged PRs

**Comment by andygolay** [comment]
Would this be manually maintained? Or is there some way to automatically update it?

**Comment by apenzk** [comment]
@andygolay to answer your above question here is a proposal how to manage this.

https://github.com/movementlabsxyz/MIP/pull/32

**Comment by apenzk** [comment]
@franck44 no statuses exist. this PR introduces a status system
https://github.com/movementlabsxyz/MIP/pull/32

**Review by apenzk — APPROVED** [review]

**Comment by andygolay** [comment]
> @andygolay to answer your above question here is a proposal how to manage this manually. We can consider automation later, but the MIPs numbering can be managed by an editor initially.
> 
> #32

Sounds good, I commented on #32.

**Review by andygolay — DISMISSED** [review]
LGTM, along with #32

**Review by andygolay — COMMENTED** [review]
I ihad originally considered this a good idea and approved it. However, after seeing the notes from yesterday's MIP meeting, I'm realizing that if an MIP is approved by a minimum of 3 org members, then it can be merged and at that point, it is considered **Accepted**. The list of accepted MIPs then is simply the MIP PRs that have been merged into the MIP repository. So an extra list, and the added bureaucracy of the associated editor role is not needed.

**Comment by andygolay** [comment]
> I ihad originally considered this a good idea and approved it. However, after seeing the notes from yesterday's MIP meeting, I'm realizing that if an MIP is approved by a minimum of 3 org members, then it can be merged and at that point, it is considered **Accepted**. The list of accepted MIPs then is simply the MIP PRs that have been merged into the MIP repository. So an extra list, and the added bureaucracy of the associated editor role is not needed.

**Comment by apenzk** [comment]
> However, after seeing the notes from yesterday's MIP meeting, I'm realizing that if an MIP is approved by a minimum of 3 org members, then it can be merged and at that point, it is considered Accepted. The list of accepted MIPs then is simply the MIP PRs that have been merged into the MIP repository. 

@andygolay this is misunderstood. the list of MIPs includes the list of unnaccepted MIPs as can be seen from the OVERVIEW file

**Comment by franck44** [comment]
@andygolay Can you just have a look again? I don't see how this MIP is a bad idea. We are trying to make it easier to navigate the MIPs. At the moment you have to list the branches to know how many we have.
What we propose is to have a list of MIPs (drafted, reviewed, updated) so that it is easy and fast to know what's happening.

**Comment by andygolay** [comment]
> @andygolay Can you just have a look again? I don't see how this MIP is a bad idea. We are trying to make it easier to navigate the MIPs. At the moment you have to list the branches to know how many we have. What we propose is to have a list of MIPs (drafted, reviewed, updated) so that it is easy and fast to know what's happening.

So, from my perspective it seems easiest to use the pulls page https://github.com/movementlabsxyz/MIP/pulls to understand where things are at, especially because it has the sorting feature.

However, maybe I misunderstood the idea of this, if it's intended more to help non-devs, in the sense that they are averse to going to GitHub, so it's more of an ancillary thing then that makes makes.

@apenzk mentioned in #32 discussion that the editor would be a non-blocking role. So I guess this isn't bad per se, it just doesn't strike me as a better organizational method than just seeing the statuses of the pull requests.

One concern I have is the amount of back-and-forth interaction the developer may have with the editor, and whether that overhead is worthwhile. 

I think with the notion clear that the editor can't block the actual MIP approval process, then I could approve these. 

Could one of you guys confirm that I'm understanding that point correctly or otherwise clarify?

**Comment by apenzk** [comment]
@andygolay yes that is correct. the role is non-blocking. If the editor is not responsive merging is fine and the editor should take care of udpates after the merge. 

A minor issue i see with this is that an [update] also requires 3 approvals for the editor. But i guess edits that were missed before the merge and have to be updated on editorial side could be batched to minimize the amount this occurs.

**Comment by andygolay** [comment]
> @andygolay yes that is correct. the role is non-blocking. If the editor is not responsive merging is fine and the editor should take care of udpates after the merge.
> 
> A minor issue i see with this is that an [update] also requires 3 approvals for the editor. But i guess edits that were missed before the merge and have to be updated could be batched to minimize the amount this occurs. But any update at any frequency should be of positive nature to the quality.

Makes sense. I'll approve. Pending resolution of the details Liam raised this seems good.

**Comment by apenzk** [comment]
@l-monninger @andygolay @franck44 
realized the overview file has to be accessed without review progress. Infact, the current location does not make sense as PRs would not be able to update the overview file on main. Not sure how this slipped me. 

I have moved it into the wiki instead which is also a git repo (so it has history) but it does not follow the reviewer requirement of the MIP repo.

This seems fine as it is for access rather than content criticial.

**Comment by franck44** [comment]
for RFCs, there is a nice rust book  implemented by Vinay [front-end](https://legendary-adventure-kgg22g7.pages.github.io/) to display the RFCs. (https://github.com/movementlabsxyz/rfcs, About section, right panel).
A similar solution could be implemented to generate the list of MIPs automatically.

This is related to @andygolay's question (indeed automated would be much better than manual):
> Would this be manually maintained? Or is there some way to automatically update it?

**Comment by apenzk** [comment]
> for RFCs, there is a nice rust book implemented by Vinay [front-end](https://legendary-adventure-kgg22g7.pages.github.io/) to display the RFCs. (https://github.com/movementlabsxyz/rfcs, About section, right panel). A similar solution could be implemented to generate the list of MIPs automatically.
> 
> This is related to @andygolay's question (indeed automated would be much better than manual):

while this is a great idea for the future. i would suggest to apply this in a different proposal / PR

**Pull request merged**
